export enum ETransactionTypes {
  RE_EMISION = 'REEMISION',
  EMISION = 'EMISION',
  TRANSFER = 'TRANSFER', 
  PAYMENT = 'PAYMENT', 
  INDIVIDUAL_INCREASE = 'INDIVIDUAL_INCREASE',
  INDIVIDUAL_DECREASE = 'INDIVIDUAL_DECREASE',
  MASSIVE_INCREMENT = 'MASSIVE_INCREMENT',
  MASSIVE_DECREMENT = 'MASSIVE_DECREMENT',
  BUY = 'BUY', 
  SELL = 'SELL', 
  EXCHANGE = 'EXCHANGE'
}