export enum ETransactionTypes {
  RE_EMISION = 'REEMISION',
  EMISION = 'EMISION',
  TRANSFER = 'TRANSFER', 
  PAYMENT = 'PAYMENT', 
  INDIVIDUAL_INCREMENT= 'INDIVIDUAL_INCREMENT', 
  INDIVIDUAL_DECREMENT= 'INDIVIDUAL_DECREMENT', 
  MASSIVE_INCREMENT = 'MASSIVE_INCREMENT', 
  MASSIVE_DECREMENT = 'MASSIVE_DECREMENT', 
  BUY = 'BUY', 
  SELL = 'SELL', 
  EXCHANGE = 'EXCHANGE'
}