export enum ETransactionTypes {
  RE_EMISION = 'REEMISION',
  EMISION = 'EMISION',
  TRANSGER = 'TRANSFER', 
  PAYMENT = 'PAYMENT', 
  INCREASE = 'INCREASE', 
  DECREASE = 'DECREASE', 
  BUY = 'BUY', 
  SELL = 'SELL', 
  EXCHANGE = 'EXCHANGE'
}